var data = [
        {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-12',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-13',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-14',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-15',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-16',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-17',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-18',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-19',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-20',
                num: '1'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '11'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '12'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '13'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '14'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '15'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '16'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '17'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '18'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '19'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '10'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '21'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '22'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '213'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '214'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '215'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '216'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '217'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '218'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '219'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '311'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '412'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '51'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '61'
        }, {
                id: '',
                snatch: '张三',
                time: '2012-12-11',
                num: '71'
        }
];
export {data};
